apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    name: nginx-deploy
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-pod
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        name: nginx-pod
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80 
          
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-service
    app: nginx-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: nginx-pod
    app: nginx-app